name: NodeJS bindings tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-nodejs-bindings:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node: [16]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Run clean/build/format/test
        run: make